export const ITEM_ADDED_TO_CART = 'ITEM_ADDED_TO_CART';
export const NAME_ENTERED = 'NAME_ENTERED';
export const EMAIL_ENTERED = 'EMAIL_ENTERED';
export const PHONE_NUMBER_ENTERED = 'PHONE_NUMBER_ENTERED';
export const CREDIT_CARD_NUMBER_ENTERED = 'CREDIT_CARD_NUMBER_ENTERED';
export const LOCATION_CHANGE = 'LOCATION_CHANGE';
